# https://taskfile.dev

version: '3'

vars:
  NAME: test

tasks:
  up:
    cmds:
      - make && make manifests
      - kubectl get ns
      - kubectl apply -k config/crd/
      - kubectl apply -k config/samples/
      - go run cmd/main.go
