---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - syoze.syoze.fr
  resources:
  - duplicators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - syoze.syoze.fr
  resources:
  - duplicators/finalizers
  verbs:
  - update
- apiGroups:
  - syoze.syoze.fr
  resources:
  - duplicators/status
  verbs:
  - get
  - patch
  - update
